name: CI/CD with Cucumber and Selenium

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      
      - name: Install dependencies
        run: bundle install

      - name: Start Selenium container
        run: |
          docker run -d \
            -p 4444:4444 \
            -p 7900:7900 \
            --shm-size="2g" \
            selenium/standalone-chrome:latest

      - name: Run tests
        run: bundle exec cucumber
  # Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    if: always() 
    needs: test 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2      
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: /logs
