name: CI/CD with Cucumber and Selenium

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      
      - name: Install dependencies
        run: bundle install

      - name: Start Selenium container
        run: |
          docker run -d \
            -p 4444:4444 \
            -p 7900:7900 \
            --shm-size="2g" \
            selenium/standalone-chrome:latest
      
      - name: Create report dir
        run: mkdir logs
      - name: Run tests
        run: bundle exec cucumber

      - uses: actions/upload-artifact@v3
        with:
          name: directory-content
          path: logs/

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: logs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
