name: CI/CD com Cucumber e Selenium

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: bundle install

    - name: Start Selenium container
      run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome

    - name: Run smoke tests
      run: bundle exec cucumber

    # Configure Pages
    - name: Configure GitHub Pages
      if: always()
      uses: actions/configure-pages@v3
    # Upload the report as a pages artifact
    - name: Upload Pages Artifact
      if: always()
      uses: actions/upload-pages-artifact@v2
      with:
        path: logs/
  # Deploy the Pages site
  deploy:
    if: always()
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2      
